services:
  - type: web
    name: nepal-connect
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16
    healthCheckPath: /gun
